medical_project/hospital_app/urls.py
from django.conf.urls import url
from hospital_app import views

app_name = 'temp'
urlpatterns = [
    #url(r'^$', views.index, name = 'index'),
    
    #url(r'^$', views.login_page, name = 'login_page'),
    url(r'^$', views.homeandh, name = 'homeandh'),
    url(r'^login_page/', views.login_page, name = 'login_page'),
    url(r'^users/', views.users, name = 'users'),
     url(r'^patient_profile/', views.patient_profile, name = 'patient_profile'),
    url(r'^sign_up_page/', views.sign_up_page, name = 'sign_up_page'),
]

medical_project/medical_project/urls.py
from django.contrib import admin
from django.urls import path, include
from hospital_app import views
from django.conf.urls import url


urlpatterns = [
      url(r'^$', views.homeandh, name = 'homeandh'),
      url(r'^hospital_app/', include('hospital_app.urls')),
      
      url(r'^$',views.index, name='index'),
     #url(r'^index/',include('hospital_app.urls')), 
     #url(r'^users/', include('hospital_app.urls')),
     #url(r'^login_page/', views.login_page, name='login_page'),
      
     url(r'^formpage/', views.form_name_view, name='form_name'),
     
     
     #url(r'^$',views.help, name='help'),
     #url(r'^help/',include('hospital_app.urls')),
     
     url(r'^admin/', admin.site.urls),
]

medical_project/templates/temp/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="styleofcontact.css">
</head>
<body>
    <section id="contact">
        <div class="content">
            <div id="form">
                <form action="" id="contactForm" method="post">
                    <span>Name</span>
                    <input type="text" name="name" class="name" placeholder="Enter your name" tabindex=1 />
                    <span>Email</span>
                    <input type="text" name="email" class="email" placeholder="Enter your email" tabindex=2 />
                    <span id="captcha"></span>
                    <input type="text" name="captcha" class="captcha" maxlength="4" size="4" placeholder="Enter captcha code" tabindex=3 />
                    <span>Message</span>
                    <textarea class="message" placeholder="Enter your message" tabindex=4></textarea>
                    <input type="submit" name="submit" value="Send e-mail" class="submit" tabindex=5>
                </form>
            </div>
</section>
<script src="contact.js"></script>
</body>
</html>

medical_project/templates/temp/form_page.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset = "utf-8">
        <title>Forms</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

         
    </head>
    <body>
        <h1> Fill out the form! </h1>
         <div class="container">
            <form  method="POST">
            {{form.as_p}}
             {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Submit">
            </form>
            
         
         </div>
                   
    </body>
</html>

medical_project/templates/temp/help.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset = "utf-8">
        <title>Hospital_app</title>
        <link rel="stylesheet" href="{% static "css/mystyle.css"%}"/>
    </head>
    <body>
        <h1>Hello welcome to our hospital app!! </h1>
        <div class="djangotwo">
           {% if access_records %}
              <table>
                <thead>
                    <th>site name</th>
                    <th>Date accessed<th/>
                </thead>
             
              {% for acc in access_records %}
              <tr>
                <td>{{acc.name}}</td>
                <td>{{acc.date}}</td>
              <tr/>
              {% endfor %}
               </table>
               {% else %}
                <p>no access records found!!</p>
                {% endif %}
        </divs>
        <img src="{% static "images/lion.jpg" %}" >        

                    
    </body>
</html>

medical_project/templates/temp/index.html
<!DOCTYPE html> {% load staticfiles %}
<html>

<head>
    <title>HOME</title>
    <meta charset="utf-8">
    <title>Hospital_app</title>
    <!--<link rel="stylesheet" href="{% static " css/mystyle.css "%}"/>-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>

<body>
    <img src="{% static  'images/slider_2.jpg' %}">
    <div class="container">
        <div class="jumbotron">
            <h1>Hello welcome to our hospital app!! </h1>

        </div>
    </div>
    <div class="djangotwo">
        {% if access_records %}
        <table>
            <thead>
                <th>site name</th>
                <th>Date accessed
                    <th/>
            </thead>

            {% for acc in access_records %}
            <tr>
                <td>{{acc.name}}</td>
                <td>{{acc.date}}</td>
            </tr> {% endfor %}
        </table>
        {% else %}
        <p>no access records found!!</p>
        {% endif %}
    </div>



</body>

</html>

medical_project/templates/temp/login_page.html
 {% load staticfiles %}{%block contents %}
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=devce-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="{% static 'Style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

</head>

<body>
    <div class="container">

        <div class="d-flex justify-content-center h-100">
            <div class="card">
                <div class="card-header">
                    <h3>Sign In</h3>

                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input type="text" class="form-control" placeholder="username">

                        </div>
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            <input type="password" class="form-control" placeholder="password">
                        </div>

                        <div class="row align-items-center remember">
                            <input type="checkbox">Remember Me
                        </div>

                        <div class="form-group">
                            <a class="btn btn-primary link" href="{% url 'temp:homeandh' %}" role="button">Sign in</a>
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-center links">
                        Don't have an account?<a href="sign_up_page.html">Sign Up</a>
                    </div>
                    <div class="d-flex justify-content-center">
                        <a href="#">Forgot your password?</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src=" //maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js "></script>
    <script src=" //cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js "></script>


</body>

</html>
{% endblock %}

medical_project/templates/temp/notification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
</head>
<body style="background-color:rgb(255, 255, 255);">
       
        
        <div class="container">
          <h1 class="page-header">Notification</h1>
        
          <h4>Notification Message</h4>
          <div class="alert alert-success">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <hr>
            <a class="alert-link" href="#">Schedule:</a> 12/23/2019 
            at 6.00 am  
            at Tirunesh Beijing hospital
            <br>
            <br>
            sent by <a href="#">Beijing hospital</a> 
          
        </div>
        
          
          
          <h4> </h4>  
        </div>
        <style>
        h4{	margin-top:50px; }
        h4 span{ font-size:13px; color:grey; }
        </style>
          <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
          <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</body>
</html>

medical_project/templates/temp/patient_profile.html
{% load staticfiles %} {% block contents %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'styleofprofile.css' %}">
    <title>Document</title>
</head>

<body>

    <div class="avatar"></div>
    <h1>Yohannis Girmaw</h1>

    <div class="container">

        <ul class="social">

            <li class="facebook">
                <a href="#" class="entypo-facebook"></a>
            </li>
            <li class="twitter">
                <a href="#" class="entypo-twitter"></a>
            </li>
            <li class="sociali">
                <a href="#" class="entypo-mouse"></a>
            </li>
            <li class="codepen">
                <a href="#" class="entypo-code"></a>
            </li>
            <li class="mail">
                <a href="#" class="entypo-mail"></a>
            </li>

        </ul>

    </div>
</body>

</html>
{% endblock %}

medical_project/templates/temp/sign_up_ page_old.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <title>sign_up</title>
</head>

<body>


    <div class="container">
        <form>

            <div class="card bg-light">

                <article class="card-body mx-auto" style="max-width: 400px;">
                    <h4 class="card-title mt-3 text-center">Create Account</h4>
                    <p class="text-center">Get started with your free account</p>


                    <form enctype="multipart/form-data" method="POST">


                        <div class="form-group input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                            </div>
                            <input name="" class="form-control" placeholder="Full name" type="text">
                        </div>
                        <!-- form-group// -->
                        <div class="form-group input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
                            </div>
                            <input name="" class="form-control" placeholder="Email address" type="email">
                        </div>


                        <!-- form-group end.// -->
                        <div class="form-group input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                            </div>
                            <input class="form-control" placeholder="Create password" type="password">
                        </div>
                        <!-- form-group// -->
                        <div class="form-group input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                            </div>
                            <input class="form-control" placeholder="Repeat password" type="password">
                        </div>
                        <!-- form-group// -->
                        <div class="container">
                            <form>

                                <a href="homeandh.html" class="btn btn-primary btn-rounded">Create_Account</a>
                            </form>
                        </div>
                        <!-- form-group// -->
                        <p class="text-center">Have an account? <a href="login_page.html">Log In</a> </p>
                    </form>
                </article>
            </div>
            <!-- card.// -->

    </div>
    <!--container end.//-->

    <br><br>
    <article class="bg-secondary mb-3">


        <br><br>
    </article>
    <script src=" //maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js "></script>
    <script src=" //cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js "></script>
</body>

</html>

medical_project/templates/temp/users.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=devce-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>users</title>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/mystyle.css' %} " />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">





</head>

<body>
    <div class="container">
        <form>
            <div class="card bg-light">
                <article class="card-body mx-auto" style="max-width: 400px;">
                    <h4 class="card-title mt-3 text-center">Create Account</h4>
                    <p class="text-center">Get started with your free account</p>

                    <form enctype="multipart/form-data" method="POST">
                        {% csrf_token %}

                        <div class="form-group input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                            </div>
                            <input name="" class="form-control" placeholder="Full name" type="text">
                        </div>

                        <div class="form-group input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
                            </div>
                            <input name="" class="form-control" placeholder="Email address" type="email">
                        </div>
                        <!----------------------------------------------------------------->>
                        <div class="form-group input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                            </div>
                            <input class="form-control" placeholder="Create password" type="password">
                        </div>
                        <!-- card.,.....................................// -->
                        <div class="form-group input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                            </div>
                            <input class="form-control" placeholder="Repeat password" type="password">
                        </div>

                        <div class="container">
                            <form>

                                <input type="submit" class="btn btn-primary btn-rounded" href="{% url 'temp:homeandh' %}" value="Create Account">
                            </form>
                        </div>



                    </form>
                </article>
            </div>
            <!-- card.// -->

    </div>
    <!-- container end...........// -->

    <br><br>
    <article class="bg-secondary mb-3">


        <br><br>
    </article>
    <script src=" //maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js "></script>
    <script src=" //cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js "></script>


</body>

</html>